import { Injectable } from '@nestjs/common';
import { SandboxPoolService } from '../database/sandbox-pool.service';
import type { PlanSignal } from '@sql-sandbox/shared';

export interface WalStats {
  walBytesBefore: bigint;
  walBytesAfter: bigint;
  walDelta: bigint;
}

/**
 * Layer 7 — WAL amplification detector.
 * Snapshots pg_stat_wal before/after DML execution and computes WAL byte delta.
 * Signals wal_amplification when WAL bytes > 10x estimated data size.
 */
@Injectable()
export class Layer7DetectorService {
  constructor(private sandbox: SandboxPoolService) {}

  private readonly WAL_QUERY = `SELECT wal_bytes FROM pg_stat_wal`;

  /**
   * Measure WAL bytes generated by a DML statement.
   * Wraps in transaction + ROLLBACK so no permanent data change occurs.
   */
  async detect(
    schemaName: string,
    sql: string,
    estimatedDataBytes: number = 0,
  ): Promise<{ walStats: WalStats | null; signals: PlanSignal[] }> {
    const client = await this.sandbox.getClient();
    let walStats: WalStats | null = null;

    try {
      await client.query(`SET search_path = "${schemaName}", public`);
      await client.query(`SET statement_timeout = '30s'`);

      // Snapshot WAL before
      const before = await client.query(this.WAL_QUERY);
      const walBytesBefore = BigInt(before.rows[0]?.wal_bytes ?? 0);

      // Execute DML inside transaction
      await client.query('BEGIN');
      await client.query(sql).catch(() => {});
      await client.query('ROLLBACK');

      // Snapshot WAL after
      const after = await client.query(this.WAL_QUERY);
      const walBytesAfter = BigInt(after.rows[0]?.wal_bytes ?? 0);
      const walDelta = walBytesAfter - walBytesBefore;

      walStats = { walBytesBefore, walBytesAfter, walDelta };
    } finally {
      await client.query('RESET ALL').catch(() => {});
      client.release();
    }

    const signals = this.buildSignals(walStats, estimatedDataBytes);
    return { walStats, signals };
  }

  private buildSignals(walStats: WalStats | null, estimatedDataBytes: number): PlanSignal[] {
    if (!walStats || walStats.walDelta <= 0n) return [];

    const signals: PlanSignal[] = [];
    const walDeltaNum = Number(walStats.walDelta);
    const walKb = (walDeltaNum / 1024).toFixed(1);

    // WAL amplification: WAL bytes > 10x estimated data size
    if (estimatedDataBytes > 0 && walDeltaNum > estimatedDataBytes * 10) {
      const amplification = (walDeltaNum / estimatedDataBytes).toFixed(1);
      signals.push({
        layer: 7,
        type: 'wal_amplification',
        severity: 'warning',
        message: `WAL amplification ${amplification}x detected — query generated ${walKb} KB of WAL for ~${(estimatedDataBytes / 1024).toFixed(1)} KB of data`,
        explanation:
          'High WAL amplification means more data is written to the write-ahead log than the actual data change. This can happen with TOAST columns, partial page writes, triggers, or unnecessary full-page writes after a checkpoint.',
        suggestion:
          'Consider: (1) using full_page_writes=off in low-risk environments, (2) reducing checkpoint frequency, (3) avoiding unnecessary TOAST by using smaller column values.',
      });
    } else if (walDeltaNum > 1024 * 1024) {
      // Always warn when WAL > 1MB regardless of data size
      signals.push({
        layer: 7,
        type: 'wal_amplification',
        severity: 'info',
        message: `Query generated ${walKb} KB of WAL writes`,
        explanation:
          'This DML operation produced a significant amount of WAL data. While expected for large writes, monitoring WAL volume helps plan replication lag and storage.',
        suggestion:
          'For bulk inserts, consider using COPY instead of individual INSERTs, and disable indexes before bulk load if possible.',
      });
    }

    return signals;
  }
}
